name: 'Terraform in DEV Environment'

on:
  push:
    branches: [ "dev" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

      env:
        AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

    - name: Terraform Plan
      run: terraform plan -input=false 
      env:
        AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    

    - name: Terraform Apply
      run: terraform apply --auto-approve
      env:
        AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

 
