name: 'Terraform in DEV Environment'

on:
  push:
    branches: [ "dev" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
  
    - name: Terraform Plan
      run: terraform plan -out=tfplan
  
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan


 
